spring:
  data:
    mongodb:
      uri: mongodb+srv://21522348:5uJVhT1HGNK003jB@cluster0.czgkfdu.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: mika
  mail:
    host: smtp.gmail.com
    port: 587
    username: 21522348@gm.uit.edu.vn
    password: ncchoiprghnaxxnt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: MIKA-BACKEND
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8080
